import { Field, ID, ObjectType } from '@nestjs/graphql';

import { tuple } from '~/utils/functions/tuple';

export const BoardTagMinimalProperties = tuple(
  'color',
  'description',
  'id',
  'name',
);

/**
 * This ObjectType represents the minimalistic version of a board tag within our GraphQL schema.
 * A board tag is essentially a label or keyword that can be affixed to tasks within a board for easier categorization and filtering.
 *
 * The BoardTagMinimalObject encapsulates the basic attributes shared across all tags, regardless of context.
 */
@ObjectType({
  description:
    'The object that is returned when a tag is gotten from a board with minimal details',
})
export class BoardTagMinimalObject {
  /**
   * Represents the color code (typically in HEX format) associated with the tag.
   * This is used for visual representation in the UI.
   */
  @Field(() => String, {
    description: 'The color of the tag',
  })
  public color?: string;

  /**
   * Provides a brief description or context about what the tag represents or its intended use.
   */
  @Field(() => String, {
    description: 'The description of the tag',
  })
  public description?: string;

  /**
   * The unique identifier for the tag, primarily generated by the database.
   * This ensures that each tag can be uniquely referenced and queried.
   */
  @Field(() => ID, {
    description: 'The id of the tag',
  })
  public id!: string;

  /**
   * The tag's display name as seen by users in the UI.
   */
  @Field(() => String, {
    description: 'The name of the tag',
  })
  public name!: string;
}
